name: hamster

on:
  push:
    branches:
      - hamster
      - develop
      - develop-2.0

jobs:
  release-build:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.17 ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: build
        run: |
          time docker build -f ./docker/substrate_builder.Dockerfile -t hamstershare/hamster:`date +%Y%m%d` .
          docker push hamstershare/hamster:`date +%Y%m%d`
          docker tag hamstershare/hamster:`date +%Y%m%d` hamstershare/substrate:latest
          docker push hamstershare/substrate:latest
